{{ if eq .Values.watchAllNamespaces "true"  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-logs-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-reader-binding-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: log-reader
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: pod-logs-reader
  apiGroup: rbac.authorization.k8s.io
{{ end }}