apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-reader
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: log-reader
            port:
              number: 8080
        path: /logs
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secretName }}
