apiVersion: v1
kind: Service
metadata:
  name: log-reader
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: log-reader
  sessionAffinity: None
  type: ClusterIP
